Resources:
  adagesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:custom.otherfile.environment.${self:provider.stage}.tableNamePrefix}adagesTable
      AttributeDefinitions:
      - AttributeName: adageId
        AttributeType: S
      - AttributeName: key
        AttributeType: S
      - AttributeName: registrationMonth
        AttributeType: N
      KeySchema:
      - AttributeName: adageId
        KeyType: HASH
      - AttributeName: key
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: registrationMonth-Index
          KeySchema:
            - AttributeName: registrationMonth
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  usersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:custom.otherfile.environment.${self:provider.stage}.tableNamePrefix}usersTable
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: key
        AttributeType: S
      - AttributeName: loginId
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: key
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: loginId-Index
          KeySchema:
            - AttributeName: loginId
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1